# -*- coding: utf-8 -*-
"""Auto-generate clock constraints for projects without an SDC:
hqbuddy -autosdc <src.hqprj> [-period <ns>] [-o out.sdc]

Elaborates the design, runs tc.autogen -print to capture the auto clock
constraint TCL lines, and writes them to a .sdc file ready for -flow/-build.
"""
import os
import re
import subprocess
import sys
import tempfile

from . import launcher


def run_autosdc(args: list) -> None:
    """Entry for 'hqbuddy -autosdc <src.hqprj> [-period ns] [-o out.sdc]'."""
    hqprj = None
    period = None
    out = None
    i = 0
    while i < len(args):
        a = args[i]
        if a == "-period" and i + 1 < len(args):
            period = args[i + 1]; i += 2
        elif a == "-o" and i + 1 < len(args):
            out = args[i + 1]; i += 2
        elif hqprj is None:
            hqprj = a; i += 1
        else:
            print(f"Error: unexpected argument: {a}")
            sys.exit(1)
    if not hqprj:
        print("Usage: hqbuddy -autosdc <src.hqprj> [-period ns] [-o out.sdc]")
        sys.exit(1)
    hqprj = os.path.abspath(hqprj)
    if not os.path.isfile(hqprj):
        print(f"Error: file not found: {hqprj}")
        sys.exit(1)
    work = os.path.dirname(hqprj)

    top = None
    srcs = []
    for ln in open(hqprj, encoding="utf-8", errors="replace"):
        ln = ln.strip()
        if ln.startswith("TOP_MODULE="):
            top = ln.split("=", 1)[1]
        elif ln.startswith("FILE_SRC=") and ln != "FILE_SRC=NONE":
            srcs.append(ln.split("=", 1)[1].replace("$WORK_DIR$", work.replace(os.sep, "/") + "/"))

    version = launcher.require_hqfpga_version()
    hqfpga_path = version["hqfpga_path"]

    vlines = "\n".join(f"lappend vfiles {s}" for s in srcs)
    auto_line = f"tc.autogen -period {period}" if period else "tc.autogen -print"
    tcl = (f"set WORK_DIR {work.replace(os.sep, '/')}\n"
           f"set vfiles {{}}\n{vlines}\n"
           f"dv.setup -synlib_only SEAL\n"
           f"rtl.analyze $vfiles\n"
           f"rtl.elaborate -top {top}\n"
           f'puts "===SDC-BEgin==="\n'
           f"{auto_line}\n"
           f'puts "===SDC-End===\n')

    tf = tempfile.NamedTemporaryFile("w", suffix=".tcl", delete=False, encoding="utf-8")
    tf.write(tcl)
    tf.close()
    proc = subprocess.run([hqfpga_path, "-cmd", tf.name], cwd=work,
                          capture_output=True, text=True,
                          errors="replace", timeout=600)
    os.unlink(tf.name)
    out_txt = proc.stdout or ""

    if "===SDC-BEgin===" not in out_txt or "===SDC-End===" not in out_txt:
        tail = "\n".join(out_txt.splitlines()[-8:])
        print(f"Error: tc.autogen 未产出约束行。hqfpga 输出尾部：\n{tail}")
        sys.exit(1)

    seg = out_txt.split("===SDC-BEgin===", 1)[1].split("===SDC-End===", 1)[0]
    sdc_lines = [l for l in seg.splitlines()
                 if l.strip() and not l.strip().startswith("===")]
    if not sdc_lines:
        print("Error: tc.autogen 产出为空。")
        sys.exit(1)

    out_path = out or os.path.join(work, "auto_generated.sdc")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("# Auto-generated by hqbuddy -autosdc (tc.autogen)\n")
        f.write(f"# top={top}  period={period or 'auto'}\n")
        f.write("\n".join(sdc_lines) + "\n")
    print(f"[OK] SDC written: {out_path} ({len(sdc_lines)} lines)")
    print("Next: hqbuddy -add <sdc> 或加入 FILE_TC 后 -build。")
