"""Flow execution: generate temp TCL and launch hqfpga -cmd."""

import os
import re
import subprocess
import sys

from . import launcher


def _generate_temp_tcl(hqprj_path: str, output_tcl: str | None = None) -> str:
    """
    Generate a temporary TCL script in the same directory as the .hqprj file.

    Args:
        hqprj_path: Path to the .hqprj file.
        output_tcl: Optional custom output TCL file name.

    Returns:
        Path to the generated temporary TCL file.
    """
    work_dir = os.path.dirname(os.path.abspath(hqprj_path))
    hqprj_abs = os.path.abspath(hqprj_path)

    # Use a fixed temp file name to avoid collisions
    temp_tcl = os.path.join(work_dir, "_hqbuddy_flow_temp.tcl")

    # Use forward slashes in TCL to avoid backslash escaping issues
    hqprj_tcl = hqprj_abs.replace("\\", "/")

    if output_tcl:
        tcl_content = f"hqprj2tcl {hqprj_tcl} {output_tcl}\n"
    else:
        tcl_content = f"hqprj2tcl {hqprj_tcl}\n"

    with open(temp_tcl, "w", encoding="utf-8") as f:
        f.write(tcl_content)

    return temp_tcl


def _make_looptdo_tcl(full_tcl_path: str) -> None:
    """
    Post-process the generated TCL for looptdo mode.

    Keeps synthesis section (everything before 'design.pack'),
    appends the looptdo command with TCL variables $SDC_FILE and $UPC_FILE.

    Args:
        full_tcl_path: Path to the TCL generated by hqprj2tcl.
    """
    with open(full_tcl_path, "r", encoding="utf-8") as f:
        lines = f.readlines()

    # Keep lines up to and including 'design.flatten' (last synthesis step)
    kept = []
    found_flatten = False
    for line in lines:
        kept.append(line)
        if line.strip().startswith("design.flatten"):
            found_flatten = True
            break

    if not found_flatten:
        print("Warning: could not locate synthesis section end (design.flatten)")
        print("Falling back to full TCL with looptdo appended.")
    else:
        # Add looptdo command with TCL variables
        kept.append("\n")
        kept.append("# Looptdo (randomized packing/placement/routing optimization)\n")
        kept.append("design.looptdo -sdc $SDC_FILE -upc $UPC_FILE -slack 0 -j 4 -timeout 1800\n")

        with open(full_tcl_path, "w", encoding="utf-8") as f:
            f.writelines(kept)

        print("Looptdo mode: synthesis preserved, pack/place/route/bitgen replaced with design.looptdo")


def _make_bin_only_tcl(full_tcl_path: str, bin_name: str | None = None) -> None:
    """
    Post-process the generated TCL for bin-only mode.

    Keeps synthesis through bitgen, but removes intermediate file writes
    (netlist dumps, XPN files, timing reports). If bin_name is provided,
    the final design.bitgen target is replaced with <bin_name>.<original_ext>;
    otherwise the original target is kept.

    Args:
        full_tcl_path: Path to the TCL generated by hqprj2tcl.
        bin_name: Optional user-specified base name for the final bitstream.
    """
    with open(full_tcl_path, "r", encoding="utf-8") as f:
        lines = f.readlines()

    # Commands that write intermediate files we want to drop
    drop_prefixes = (
        "nl.write",
        "nl.report",
        "xpn.write",
        "ta.report",
        "ta.fmax.report",
    )

    kept = []
    bitgen_ext = None
    bitgen_idx = None

    for i, line in enumerate(lines):
        stripped = line.strip()

        # Drop intermediate file output commands
        if any(stripped.startswith(p) for p in drop_prefixes):
            continue

        # Locate design.bitgen and extract original extension
        if stripped.startswith("design.bitgen"):
            parts = stripped.split()
            if len(parts) >= 2:
                original_target = parts[1]
                _, ext = os.path.splitext(original_target)
                if ext:
                    bitgen_ext = ext  # e.g. ".bit" or ".bin"
            bitgen_idx = len(kept)
            kept.append(line)
            continue

        kept.append(line)

    if bitgen_idx is None:
        print("Error: could not locate design.bitgen command in generated TCL")
        sys.exit(1)

    if not bitgen_ext:
        print("Warning: could not detect bitgen extension; defaulting to .bit")
        bitgen_ext = ".bit"

    if bin_name is not None:
        # Normalize user-provided name: strip any known bitstream extension,
        # then append the original script extension
        known_exts = (".bit", ".bin")
        clean_name = bin_name
        for ext in known_exts:
            if clean_name.lower().endswith(ext):
                clean_name = clean_name[:-len(ext)]
                break
        final_target = f"{clean_name}{bitgen_ext}"

        # Rewrite design.bitgen line, preserving any extra arguments
        original_line = kept[bitgen_idx]
        kept[bitgen_idx] = re.sub(
            r"(design\.bitgen\s+)\S+",
            rf"\g<1>{final_target}",
            original_line,
        )
    else:
        # Keep original bitgen target
        original_line = kept[bitgen_idx].strip()
        parts = original_line.split()
        final_target = parts[1] if len(parts) >= 2 else "<unknown>"

    with open(full_tcl_path, "w", encoding="utf-8") as f:
        f.writelines(kept)

    print(f"Bin-only mode: intermediate file writes removed; bitgen target -> {final_target}")


def _run_hqfpga(hqfpga_path: str, temp_tcl: str, work_dir: str) -> None:
    """Run hqfpga with the given temp TCL in the work directory."""
    cmd = [hqfpga_path, "-cmd", temp_tcl]
    print(f"Launching: {' '.join(cmd)}")
    print("")

    proc = subprocess.Popen(cmd, cwd=work_dir)
    try:
        proc.wait()
    except KeyboardInterrupt:
        proc.terminate()
        try:
            proc.wait(timeout=5)
        except subprocess.TimeoutExpired:
            proc.kill()
            proc.wait()
        raise

    if proc.returncode != 0:
        print(f"")
        print(f"Warning: hqfpga exited with code {proc.returncode}")


def _resolve_hqfpga() -> str:
    """Resolve hqfpga path or exit with error."""
    version = launcher.resolve_hqfpga_version()
    if not version:
        print("Error: no HqFPGA versions found.")
        print("Tip: Use 'hqbuddy -cfg' to edit the scan roots in config.json.")
        sys.exit(1)
    return version['hqfpga_path']


def run_flow(hqprj_path: str, output_tcl: str | None = None) -> None:
    """
    Run the flow command: generate temp TCL and execute via hqfpga (normal mode).

    Args:
        hqprj_path: Path to the .hqprj file.
        output_tcl: Optional custom output TCL file name.
    """
    if not os.path.isfile(hqprj_path):
        print(f"Error: file not found: {hqprj_path}")
        sys.exit(1)

    work_dir = os.path.dirname(os.path.abspath(hqprj_path))
    hqfpga_path = _resolve_hqfpga()

    # Generate temporary TCL
    temp_tcl = _generate_temp_tcl(hqprj_path, output_tcl)

    try:
        print(f"Generated temp TCL: {temp_tcl}")
        _run_hqfpga(hqfpga_path, temp_tcl, work_dir)
    finally:
        if os.path.exists(temp_tcl):
            os.remove(temp_tcl)
            print(f"")
            print(f"Cleaned up temp TCL: {temp_tcl}")


def run_flow_looptdo(hqprj_path: str, output_tcl: str | None = None) -> None:
    """
    Run the flow in looptdo mode.

    Generates the full TCL via hqprj2tcl, then post-processes it to keep
    only the synthesis section and adds the looptdo command.

    Args:
        hqprj_path: Path to the .hqprj file.
        output_tcl: Optional custom output TCL file name.
    """
    if not os.path.isfile(hqprj_path):
        print(f"Error: file not found: {hqprj_path}")
        sys.exit(1)

    work_dir = os.path.dirname(os.path.abspath(hqprj_path))
    hqfpga_path = _resolve_hqfpga()

    # Generate the full TCL via hqprj2tcl first
    temp_tcl = _generate_temp_tcl(hqprj_path, output_tcl)

    try:
        print(f"Generated temp TCL: {temp_tcl}")

        # Run hqprj2tcl to generate the full flow TCL
        _run_hqfpga(hqfpga_path, temp_tcl, work_dir)

        # Determine the output TCL path (the one hqprj2tcl wrote to)
        if output_tcl:
            flow_tcl = os.path.join(work_dir, output_tcl)
        else:
            flow_tcl = os.path.join(work_dir, "run_hqprj.tcl")

        if not os.path.isfile(flow_tcl):
            print(f"Error: hqprj2tcl did not generate expected TCL: {flow_tcl}")
            sys.exit(1)

        # Post-process for looptdo
        _make_looptdo_tcl(flow_tcl)
        print(f"Looptdo TCL ready: {os.path.abspath(flow_tcl)}")

    finally:
        if os.path.exists(temp_tcl):
            os.remove(temp_tcl)
            print(f"")
            print(f"Cleaned up temp TCL: {temp_tcl}")


def run_flow_bin_only(hqprj_path: str, bin_name: str | None = None, output_tcl: str | None = None) -> None:
    """
    Run the flow in bin-only mode.

    Generates the full TCL via hqprj2tcl, then trims it to remove all
    intermediate file writes. If bin_name is provided, the final bitgen
    target is replaced with that name; otherwise the original target is kept.

    Args:
        hqprj_path: Path to the .hqprj file.
        bin_name: Optional user-specified base name for the final bitstream.
        output_tcl: Optional custom output TCL file name.
    """
    if not os.path.isfile(hqprj_path):
        print(f"Error: file not found: {hqprj_path}")
        sys.exit(1)

    work_dir = os.path.dirname(os.path.abspath(hqprj_path))
    hqfpga_path = _resolve_hqfpga()

    # Generate the full TCL via hqprj2tcl first
    temp_tcl = _generate_temp_tcl(hqprj_path, output_tcl)

    try:
        print(f"Generated temp TCL: {temp_tcl}")

        # Run hqprj2tcl to generate the full flow TCL
        _run_hqfpga(hqfpga_path, temp_tcl, work_dir)

        # Determine the output TCL path (the one hqprj2tcl wrote to)
        if output_tcl:
            flow_tcl = os.path.join(work_dir, output_tcl)
        else:
            flow_tcl = os.path.join(work_dir, "run_hqprj.tcl")

        if not os.path.isfile(flow_tcl):
            print(f"Error: hqprj2tcl did not generate expected TCL: {flow_tcl}")
            sys.exit(1)

        # Post-process for bin-only mode
        _make_bin_only_tcl(flow_tcl, bin_name)
        print(f"Bin-only TCL ready: {os.path.abspath(flow_tcl)}")

    finally:
        if os.path.exists(temp_tcl):
            os.remove(temp_tcl)
            print(f"")
            print(f"Cleaned up temp TCL: {temp_tcl}")
