"""Flow execution: generate temp TCL and launch hqfpga -cmd."""

import os
import subprocess
import sys

from . import launcher


def _generate_temp_tcl(hqprj_path: str, output_tcl: str | None = None) -> str:
    """
    Generate a temporary TCL script in the same directory as the .hqprj file.

    Args:
        hqprj_path: Path to the .hqprj file.
        output_tcl: Optional custom output TCL file name.

    Returns:
        Path to the generated temporary TCL file.
    """
    work_dir = os.path.dirname(os.path.abspath(hqprj_path))
    hqprj_abs = os.path.abspath(hqprj_path)

    # Use a fixed temp file name to avoid collisions
    temp_tcl = os.path.join(work_dir, "_hqbuddy_flow_temp.tcl")

    # Use forward slashes in TCL to avoid backslash escaping issues
    hqprj_tcl = hqprj_abs.replace("\\", "/")

    if output_tcl:
        tcl_content = f"hqprj2tcl {hqprj_tcl} {output_tcl}\n"
    else:
        tcl_content = f"hqprj2tcl {hqprj_tcl}\n"

    with open(temp_tcl, "w", encoding="utf-8") as f:
        f.write(tcl_content)

    return temp_tcl


def _make_looptdo_tcl(full_tcl_path: str) -> None:
    """
    Post-process the generated TCL for looptdo mode.

    Keeps synthesis section (everything before 'design.pack'),
    appends the looptdo command with TCL variables $SDC_FILE and $UPC_FILE.

    Args:
        full_tcl_path: Path to the TCL generated by hqprj2tcl.
    """
    with open(full_tcl_path, "r", encoding="utf-8") as f:
        lines = f.readlines()

    # Keep lines up to and including 'design.flatten' (last synthesis step)
    kept = []
    found_flatten = False
    for line in lines:
        kept.append(line)
        if line.strip().startswith("design.flatten"):
            found_flatten = True
            break

    if not found_flatten:
        print("Warning: could not locate synthesis section end (design.flatten)")
        print("Falling back to full TCL with looptdo appended.")
    else:
        # Add looptdo command with TCL variables
        kept.append("\n")
        kept.append("# Looptdo (randomized packing/placement/routing optimization)\n")
        kept.append("design.looptdo -sdc $SDC_FILE -upc $UPC_FILE -slack 0 -j 4 -timeout 1800\n")

        with open(full_tcl_path, "w", encoding="utf-8") as f:
            f.writelines(kept)

        print("Looptdo mode: synthesis preserved, pack/place/route/bitgen replaced with design.looptdo")


def _run_hqfpga(hqfpga_path: str, temp_tcl: str, work_dir: str) -> None:
    """Run hqfpga with the given temp TCL in the work directory."""
    cmd = [hqfpga_path, "-cmd", temp_tcl]
    print(f"Launching: {' '.join(cmd)}")
    print("")

    proc = subprocess.Popen(cmd, cwd=work_dir)
    try:
        proc.wait()
    except KeyboardInterrupt:
        proc.terminate()
        try:
            proc.wait(timeout=5)
        except subprocess.TimeoutExpired:
            proc.kill()
            proc.wait()
        raise

    if proc.returncode != 0:
        print(f"")
        print(f"Warning: hqfpga exited with code {proc.returncode}")


def _resolve_hqfpga() -> str:
    """Resolve hqfpga path or exit with error."""
    version = launcher.resolve_hqfpga_version()
    if not version:
        print("Error: no HqFPGA versions found.")
        print("Tip: Use 'hqbuddy -cfg auto' to configure scan roots.")
        sys.exit(1)
    return version['hqfpga_path']


def run_flow(hqprj_path: str, output_tcl: str | None = None) -> None:
    """
    Run the flow command: generate temp TCL and execute via hqfpga (normal mode).

    Args:
        hqprj_path: Path to the .hqprj file.
        output_tcl: Optional custom output TCL file name.
    """
    if not os.path.isfile(hqprj_path):
        print(f"Error: file not found: {hqprj_path}")
        sys.exit(1)

    work_dir = os.path.dirname(os.path.abspath(hqprj_path))
    hqfpga_path = _resolve_hqfpga()

    # Generate temporary TCL
    temp_tcl = _generate_temp_tcl(hqprj_path, output_tcl)

    try:
        print(f"Generated temp TCL: {temp_tcl}")
        _run_hqfpga(hqfpga_path, temp_tcl, work_dir)
    finally:
        if os.path.exists(temp_tcl):
            os.remove(temp_tcl)
            print(f"")
            print(f"Cleaned up temp TCL: {temp_tcl}")


def run_flow_looptdo(hqprj_path: str, output_tcl: str | None = None) -> None:
    """
    Run the flow in looptdo mode.

    Generates the full TCL via hqprj2tcl, then post-processes it to keep
    only the synthesis section and adds the looptdo command.

    Args:
        hqprj_path: Path to the .hqprj file.
        output_tcl: Optional custom output TCL file name.
    """
    if not os.path.isfile(hqprj_path):
        print(f"Error: file not found: {hqprj_path}")
        sys.exit(1)

    work_dir = os.path.dirname(os.path.abspath(hqprj_path))
    hqfpga_path = _resolve_hqfpga()

    # Generate the full TCL via hqprj2tcl first
    temp_tcl = _generate_temp_tcl(hqprj_path, output_tcl)

    try:
        print(f"Generated temp TCL: {temp_tcl}")

        # Run hqprj2tcl to generate the full flow TCL
        _run_hqfpga(hqfpga_path, temp_tcl, work_dir)

        # Determine the output TCL path (the one hqprj2tcl wrote to)
        if output_tcl:
            flow_tcl = os.path.join(work_dir, output_tcl)
        else:
            flow_tcl = os.path.join(work_dir, "run_hqprj.tcl")

        if not os.path.isfile(flow_tcl):
            print(f"Error: hqprj2tcl did not generate expected TCL: {flow_tcl}")
            sys.exit(1)

        # Post-process for looptdo
        _make_looptdo_tcl(flow_tcl)
        print(f"Looptdo TCL ready: {os.path.abspath(flow_tcl)}")

    finally:
        if os.path.exists(temp_tcl):
            os.remove(temp_tcl)
            print(f"")
            print(f"Cleaned up temp TCL: {temp_tcl}")
