"""Flow execution: generate temp TCL and launch hqfpga -cmd."""

import glob
import os
import re
import shutil
import subprocess
import sys
import time

from . import launcher


def _generate_temp_tcl(hqprj_path: str, output_tcl: str | None = None) -> str:
    """
    Generate a temporary TCL script in the same directory as the .hqprj file.

    Args:
        hqprj_path: Path to the .hqprj file.
        output_tcl: Optional custom output TCL file name.

    Returns:
        Path to the generated temporary TCL file.
    """
    work_dir = os.path.dirname(os.path.abspath(hqprj_path))
    hqprj_abs = os.path.abspath(hqprj_path)

    # Use a fixed temp file name to avoid collisions
    temp_tcl = os.path.join(work_dir, "_hqbuddy_flow_temp.tcl")

    # Use forward slashes in TCL to avoid backslash escaping issues
    hqprj_tcl = hqprj_abs.replace("\\", "/")

    if output_tcl:
        tcl_content = f"hqprj2tcl {hqprj_tcl} {output_tcl}\n"
    else:
        tcl_content = f"hqprj2tcl {hqprj_tcl}\n"

    with open(temp_tcl, "w", encoding="utf-8") as f:
        f.write(tcl_content)

    return temp_tcl


def _make_looptdo_tcl(full_tcl_path: str) -> None:
    """
    Post-process the generated TCL for looptdo mode.

    Keeps synthesis section (everything before 'design.pack'),
    appends the looptdo command with TCL variables $SDC_FILE and $UPC_FILE.

    Args:
        full_tcl_path: Path to the TCL generated by hqprj2tcl.
    """
    with open(full_tcl_path, "r", encoding="utf-8") as f:
        lines = f.readlines()

    # Keep lines up to and including 'design.flatten' (last synthesis step)
    kept = []
    found_flatten = False
    for line in lines:
        kept.append(line)
        if line.strip().startswith("design.flatten"):
            found_flatten = True
            break

    if not found_flatten:
        print("Warning: could not locate synthesis section end (design.flatten)")
        print("Falling back to full TCL with looptdo appended.")
    else:
        # Add looptdo command with TCL variables
        kept.append("\n")
        kept.append("# Looptdo (randomized packing/placement/routing optimization)\n")
        kept.append("design.looptdo -sdc $SDC_FILE -upc $UPC_FILE -slack 0 -j 4 -timeout 1800\n")

        with open(full_tcl_path, "w", encoding="utf-8") as f:
            f.writelines(kept)

        print("Looptdo mode: synthesis preserved, pack/place/route/bitgen replaced with design.looptdo")


def _make_bin_only_tcl(full_tcl_path: str, bin_name: str | None = None) -> None:
    """
    Post-process the generated TCL for bin-only mode.

    Keeps synthesis through bitgen, but removes intermediate file writes
    (netlist dumps, XPN files, timing reports). If bin_name is provided,
    the final design.bitgen target is replaced with <bin_name>.<original_ext>;
    otherwise the original target is kept.

    Args:
        full_tcl_path: Path to the TCL generated by hqprj2tcl.
        bin_name: Optional user-specified base name for the final bitstream.
    """
    with open(full_tcl_path, "r", encoding="utf-8") as f:
        lines = f.readlines()

    # Commands that write intermediate files we want to drop
    drop_prefixes = (
        "nl.write",
        "nl.report",
        "xpn.write",
        "ta.report",
        "ta.fmax.report",
    )

    kept = []
    bitgen_ext = None
    bitgen_idx = None

    for i, line in enumerate(lines):
        stripped = line.strip()

        # Drop intermediate file output commands
        if any(stripped.startswith(p) for p in drop_prefixes):
            continue

        # Locate design.bitgen and extract original extension
        if stripped.startswith("design.bitgen"):
            parts = stripped.split()
            if len(parts) >= 2:
                original_target = parts[1]
                _, ext = os.path.splitext(original_target)
                if ext:
                    bitgen_ext = ext  # e.g. ".bit" or ".bin"
            bitgen_idx = len(kept)
            kept.append(line)
            continue

        kept.append(line)

    if bitgen_idx is None:
        print("Error: could not locate design.bitgen command in generated TCL")
        sys.exit(1)

    if not bitgen_ext:
        print("Warning: could not detect bitgen extension; defaulting to .bit")
        bitgen_ext = ".bit"

    if bin_name is not None:
        # Normalize user-provided name: strip any known bitstream extension,
        # then append the original script extension
        known_exts = (".bit", ".bin")
        clean_name = bin_name
        for ext in known_exts:
            if clean_name.lower().endswith(ext):
                clean_name = clean_name[:-len(ext)]
                break
        final_target = f"{clean_name}{bitgen_ext}"

        # Rewrite design.bitgen line, preserving any extra arguments
        original_line = kept[bitgen_idx]
        kept[bitgen_idx] = re.sub(
            r"(design\.bitgen\s+)\S+",
            rf"\g<1>{final_target}",
            original_line,
        )
    else:
        # Keep original bitgen target
        original_line = kept[bitgen_idx].strip()
        parts = original_line.split()
        final_target = parts[1] if len(parts) >= 2 else "<unknown>"

    with open(full_tcl_path, "w", encoding="utf-8") as f:
        f.writelines(kept)

    print(f"Bin-only mode: intermediate file writes removed; bitgen target -> {final_target}")


def _run_hqfpga(hqfpga_path: str, temp_tcl: str, work_dir: str) -> None:
    """Run hqfpga with the given temp TCL in the work directory."""
    cmd = [hqfpga_path, "-cmd", temp_tcl]
    print(f"Launching: {' '.join(cmd)}")
    print("")

    proc = subprocess.Popen(cmd, cwd=work_dir)
    try:
        proc.wait()
    except KeyboardInterrupt:
        proc.terminate()
        try:
            proc.wait(timeout=5)
        except subprocess.TimeoutExpired:
            proc.kill()
            proc.wait()
        raise

    if proc.returncode != 0:
        print(f"")
        print(f"Warning: hqfpga exited with code {proc.returncode}")


def _resolve_hqfpga() -> str:
    """Resolve hqfpga path or exit with error."""
    version = launcher.require_hqfpga_version()
    return version['hqfpga_path']


def _fresh_bitstream(work_dir: str, since: float) -> str | None:
    """Return the newest .bin/.bit produced after `since`, or None. The flow
    can exit 0 while bitgen actually failed, so the artifact (not the exit
    code) is truth."""
    candidates = []
    for pat in ("*.bin", "*.bit"):
        candidates.extend(glob.glob(os.path.join(work_dir, pat)))
        candidates.extend(glob.glob(os.path.join(work_dir, "hq_run", pat)))
    fresh = [p for p in candidates if os.path.getmtime(p) >= since]
    if not fresh:
        return None
    return max(fresh, key=os.path.getmtime)


def _check_bitstream(work_dir: str, since: float) -> None:
    """Verify a fresh bitstream was produced; the flow can exit 0 while
    bitgen actually failed, so the artifact (not the exit code) is truth."""
    if _fresh_bitstream(work_dir, since) is None:
        print("")
        print("Error: flow finished but no fresh .bin/.bit was produced "
              "(bitgen likely failed). Check hqfpga.log and the .rpt reports.")
        sys.exit(1)


def run_flow(hqprj_path: str, output_tcl: str | None = None) -> None:
    """
    Run the flow command: generate temp TCL and execute via hqfpga (normal mode).

    Args:
        hqprj_path: Path to the .hqprj file.
        output_tcl: Optional custom output TCL file name.
    """
    if not os.path.isfile(hqprj_path):
        print(f"Error: file not found: {hqprj_path}")
        sys.exit(1)

    work_dir = os.path.dirname(os.path.abspath(hqprj_path))
    hqfpga_path = _resolve_hqfpga()

    # Generate temporary TCL
    temp_tcl = _generate_temp_tcl(hqprj_path, output_tcl)

    try:
        print(f"Generated temp TCL: {temp_tcl}")
        _run_hqfpga(hqfpga_path, temp_tcl, work_dir)
    finally:
        if os.path.exists(temp_tcl):
            os.remove(temp_tcl)
            print(f"")
            print(f"Cleaned up temp TCL: {temp_tcl}")

    # per-project synthesis option overrides (-synopt sidecar)
    from .synopt import load_overrides, inject_synopt
    full_tcl = os.path.join(work_dir, "run_hqprj.tcl")
    if os.path.isfile(full_tcl) and load_overrides(hqprj_path):
        lines = open(full_tcl, encoding="utf-8", errors="replace").read().splitlines()
        lines = inject_synopt(lines, hqprj_path)
        with open(full_tcl, "w", encoding="utf-8", newline="") as f:
            f.write(chr(10).join(lines) + chr(10))


def run_flow_looptdo(hqprj_path: str, output_tcl: str | None = None) -> None:
    """
    Run the flow in looptdo mode.

    Generates the full TCL via hqprj2tcl, then post-processes it to keep
    only the synthesis section and adds the looptdo command.

    Args:
        hqprj_path: Path to the .hqprj file.
        output_tcl: Optional custom output TCL file name.
    """
    if not os.path.isfile(hqprj_path):
        print(f"Error: file not found: {hqprj_path}")
        sys.exit(1)

    work_dir = os.path.dirname(os.path.abspath(hqprj_path))
    hqfpga_path = _resolve_hqfpga()

    # Generate the full TCL via hqprj2tcl first
    temp_tcl = _generate_temp_tcl(hqprj_path, output_tcl)

    try:
        print(f"Generated temp TCL: {temp_tcl}")

        # Run hqprj2tcl to generate the full flow TCL
        _run_hqfpga(hqfpga_path, temp_tcl, work_dir)

        # Determine the output TCL path (the one hqprj2tcl wrote to)
        if output_tcl:
            flow_tcl = os.path.join(work_dir, output_tcl)
        else:
            flow_tcl = os.path.join(work_dir, "run_hqprj.tcl")

        if not os.path.isfile(flow_tcl):
            print(f"Error: hqprj2tcl did not generate expected TCL: {flow_tcl}")
            sys.exit(1)

        # Post-process for looptdo
        _make_looptdo_tcl(flow_tcl)
        print(f"Looptdo TCL ready: {os.path.abspath(flow_tcl)}")

    finally:
        if os.path.exists(temp_tcl):
            os.remove(temp_tcl)
            print(f"")
            print(f"Cleaned up temp TCL: {temp_tcl}")


def run_flow_bin_only(hqprj_path: str, bin_name: str | None = None, output_tcl: str | None = None) -> None:
    """
    Run the flow in bin-only mode.

    Generates the full TCL via hqprj2tcl, then trims it to remove all
    intermediate file writes. If bin_name is provided, the final bitgen
    target is replaced with that name; otherwise the original target is kept.

    Args:
        hqprj_path: Path to the .hqprj file.
        bin_name: Optional user-specified base name for the final bitstream.
        output_tcl: Optional custom output TCL file name.
    """
    if not os.path.isfile(hqprj_path):
        print(f"Error: file not found: {hqprj_path}")
        sys.exit(1)

    work_dir = os.path.dirname(os.path.abspath(hqprj_path))
    hqfpga_path = _resolve_hqfpga()

    # Generate the full TCL via hqprj2tcl first
    temp_tcl = _generate_temp_tcl(hqprj_path, output_tcl)

    try:
        print(f"Generated temp TCL: {temp_tcl}")

        # Run hqprj2tcl to generate the full flow TCL
        _run_hqfpga(hqfpga_path, temp_tcl, work_dir)

        # Determine the output TCL path (the one hqprj2tcl wrote to)
        if output_tcl:
            flow_tcl = os.path.join(work_dir, output_tcl)
        else:
            flow_tcl = os.path.join(work_dir, "run_hqprj.tcl")

        if not os.path.isfile(flow_tcl):
            print(f"Error: hqprj2tcl did not generate expected TCL: {flow_tcl}")
            sys.exit(1)

        # Post-process for bin-only mode
        _make_bin_only_tcl(flow_tcl, bin_name)
        print(f"Bin-only TCL ready: {os.path.abspath(flow_tcl)}")

    finally:
        if os.path.exists(temp_tcl):
            os.remove(temp_tcl)
            print(f"")
            print(f"Cleaned up temp TCL: {temp_tcl}")


def _extract_sweep_parts(lines: list) -> dict:
    """Pull the pieces out of an hqprj2tcl flow script for seed sweep mode:
    the synthesis section (everything through design.flatten), the constraint
    block (tc.clear + sdc/upc foreach sitting between flatten and pack), and
    the P&R/report/bitgen commands kept verbatim. Per-seed TCLs re-emit the
    P&R commands unchanged — their writers all take cwd-relative filenames,
    and each seed runs with cwd=<its own seed dir>."""
    flatten_idx = next((i for i, ln in enumerate(lines)
                        if ln.strip().startswith("design.flatten")), None)
    pack_idx = next((i for i, ln in enumerate(lines)
                     if ln.strip().startswith(("design.pack", "impl.pack"))), None)
    if flatten_idx is None or pack_idx is None or flatten_idx >= pack_idx:
        print("Error: cannot split synthesis from P&R in generated TCL "
              "(need design.flatten followed by design.pack)")
        sys.exit(1)

    def _last_cmd(*prefixes: str) -> str | None:
        for ln in reversed(lines):
            s = ln.strip()
            if any(s.startswith(p) for p in prefixes):
                return s
        return None

    pack_cmd = _last_cmd("design.pack", "impl.pack")
    place_cmd = _last_cmd("design.place", "impl.place")
    route_cmd = _last_cmd("design.route", "impl.route")
    bitgen_cmd = _last_cmd("design.bitgen", "impl.bitgen")
    fmax_cmd = _last_cmd("ta.fmax.report")
    ta_cmd = _last_cmd("ta.report")  # the post-route one
    # routed physical netlist: the flow's LAST xpn.write (after design.route;
    # earlier ones dump the packed/placed netlist and stay dropped)
    xpn_cmd = _last_cmd("xpn.write")
    # place utilization report: the nl.report line carrying -location
    place_rpt_cmd = next((ln.strip() for ln in lines
                          if ln.strip().startswith("nl.report") and "-location" in ln),
                         None)

    if not all((place_cmd, route_cmd, bitgen_cmd, ta_cmd)):
        print("Error: could not locate place/route/bitgen/timing-report steps "
              "in generated TCL")
        sys.exit(1)

    # the sweep owns -seed; strip any fixed value so seeds really differ
    place_cmd = re.sub(r"\s+-seed\s+\S+", "", place_cmd)

    return {
        "synth_lines": lines[:flatten_idx + 1],
        "constraint_block": lines[flatten_idx + 1:pack_idx],
        "constraint_sets": [ln for ln in lines[:flatten_idx + 1]
                            if ln.strip().startswith(("set SDC_FILE", "set UPC_FILE",
                                                      "set TOP_MODULE"))],
        "pack_cmd": pack_cmd,
        "place_cmd": place_cmd,
        "route_cmd": route_cmd,
        "bitgen_cmd": bitgen_cmd,
        "fmax_cmd": fmax_cmd,
        "ta_cmd": ta_cmd,
        "xpn_cmd": xpn_cmd,
        "place_rpt_cmd": place_rpt_cmd,
    }


def _build_synth_tcl(parts: dict, udb_abs: str) -> str:
    """Synthesis-only TCL: run synthesis once, then design.save the
    post-flatten design into a shared UDB for the per-seed P&R runs."""
    return "".join(parts["synth_lines"]) + "\n" + f"design.save {udb_abs}\n"


def _build_seed_tcl(parts: dict, seed: int, udb_abs: str) -> str:
    """Per-seed P&R TCL. design.load clears ALL in-memory design data before
    reloading the UDB, so every seed starts from the same post-synthesis
    state (a bare re-pack would accumulate placement state and fail with
    e.g. PHY-PLA-665 OSC capacity overflow). UDB does not store timing
    constraints, so the SDC/UPC block is re-emitted; effort stays fixed,
    only -seed varies. Reports/bitstream land in the seed's own cwd."""
    lines = [
        "# hqbuddy seed sweep: P&R for one seed; synthesis is shared via the UDB\n",
    ]
    lines += parts["constraint_sets"]
    lines += ["\n", f"design.load {udb_abs}\n", "\n"]
    lines += parts["constraint_block"]
    lines += [
        f"{parts['pack_cmd']}\n",
        f"{parts['place_cmd']} -seed {seed}\n",
    ]
    if parts["place_rpt_cmd"]:
        lines.append(f"{parts['place_rpt_cmd']}\n")
    lines.append(f"{parts['route_cmd']}\n")
    if parts["xpn_cmd"]:
        lines.append(f"{parts['xpn_cmd']}\n")
    if parts["fmax_cmd"]:
        lines.append(f"{parts['fmax_cmd']}\n")
    lines.append(f"{parts['ta_cmd']}\n")
    lines.append(f"{parts['bitgen_cmd']}\n")
    return "".join(lines)


def run_seed_sweep(hqprj_path: str, n: int = 3, j: int = 4, ins: bool = False,
                   no_dl: bool = False) -> None:
    """Multi-seed P&R sweep: synthesize once into a shared UDB, then run the
    per-seed P&R (pack/place/route/bitgen, fixed effort, only the placement
    -seed varies) as up to -j parallel hqfpga processes, each isolated in
    <prj_dir>/seed_sweep/seed<k>/. seed_sweep_summary.csv collects WNS/Fmax.

    With ins=True, sweep the HqInsight-instrumented derived project
    (hqins_run/hq_import/hqins_impl.hqprj) instead, so every seed's bitstream
    carries the VLA probes; artifacts go to <prj_dir>/seed_sweep_ins/ to stay
    out of hqins_run/. The instrumented artifacts (insight_ip.v +
    hq_import_with_bscan.v) are force-rebuilt first (run_refresh) — file-list
    staleness checks cannot see IP-internal includes — then the official insight
    flow (run_hqprj2hqins_flow) refreshes the derived project and canonical bit.

    design.place/impl.place natively support -seed <value> (R54 probe)."""
    from .report import _parse_fmax, _parse_wns

    if not os.path.isfile(hqprj_path):
        print(f"Error: file not found: {hqprj_path}")
        sys.exit(1)
    work_dir = os.path.dirname(os.path.abspath(hqprj_path))
    # FILE_TC 预检：sweep 的 TCL 由 hqprj2tcl 生成，工程无时序约束时它半路失败
    # （实测），提前给出可操作的报错。
    m_tc = re.search(r"^FILE_TC=(.*)$",
                     open(hqprj_path, encoding="utf-8", errors="replace").read(), re.M)
    tc = m_tc.group(1).strip() if m_tc else ""
    if not tc or tc.upper() == "NONE":
        print("Error: .hqprj 未配置 FILE_TC（时序约束）——seed_sweep 的 TCL 生成会失败。")
        print("       请先在 .hqprj 中设置 FILE_TC=$WORK_DIR$<sdc 路径>（或用 GUI 挂约束）再重试。")
        sys.exit(1)
    if ins:
        from . import insight
        proj = insight.resolve_insight_project(hqprj_path, require_hqins=True)
        info = insight._load_signal_info(proj)
        sigs = insight._collect_signals(info) if info else []
        if not sigs:
            print("Error: no probe signals selected — add some first "
                  "(hqbuddy -insight -add <signal>).")
            sys.exit(1)
        # 强制重建插桩产物：文件清单 staleness 检测对 IP 内部 include 无解
        # （改 IP 内部文件不会体现在任何 FILE_SRC 清单里），每次重建才可靠，
        # 顺带自愈网表/insight_ip.v 被删后的 HQINS001。
        print(f"[ins] Rebuilding instrumented artifacts (refresh) for {proj['hqprj']} ...")
        insight.run_refresh(proj)
        print("[ins] Running official insight flow (implementation) ...")
        insight.run_flow(proj)
        impl_prj = os.path.join(proj["hqins_dir"], "hq_import", "hqins_impl.hqprj")
        if not os.path.isfile(impl_prj):
            print(f"Error: instrumented derived project not found: {impl_prj}")
            sys.exit(1)
        hqprj_path = impl_prj
        sweep_dir = os.path.join(work_dir, "seed_sweep_ins")
    else:
        sweep_dir = os.path.join(work_dir, "seed_sweep")
    os.makedirs(sweep_dir, exist_ok=True)
    hqfpga_path = _resolve_hqfpga()
    top = None
    m_top = re.search(r"TOP_MODULE[= ]+(\S+)",
                      open(hqprj_path, encoding="utf-8", errors="replace").read())
    if m_top:
        top = m_top.group(1)

    # 1. generate the base flow TCL inside the sweep dir (hqprj2tcl writes
    #    relative to cwd), so the project root stays clean
    temp_tcl = os.path.join(sweep_dir, "_hqbuddy_sweep_temp.tcl")
    hqprj_tcl = os.path.abspath(hqprj_path).replace("\\", "/")
    with open(temp_tcl, "w", encoding="utf-8") as f:
        f.write(f"hqprj2tcl {hqprj_tcl} run_hqprj.tcl\n")
    try:
        _run_hqfpga(hqfpga_path, temp_tcl, sweep_dir)
    finally:
        if os.path.exists(temp_tcl):
            os.remove(temp_tcl)
    tcl_path = os.path.join(sweep_dir, "run_hqprj.tcl")
    if not os.path.isfile(tcl_path):
        print(f"Error: hqprj2tcl did not generate expected TCL: {tcl_path}")
        sys.exit(1)

    # per-project synthesis option overrides (-synopt sidecar), same as -flow
    from .synopt import inject_synopt, load_overrides
    lines = open(tcl_path, encoding="utf-8", errors="replace").read().splitlines()
    if load_overrides(hqprj_path):
        lines = inject_synopt(lines, hqprj_path)
        with open(tcl_path, "w", encoding="utf-8", newline="") as f:
            f.write(chr(10).join(lines) + chr(10))
    lines = open(tcl_path, encoding="utf-8", errors="replace").readlines()
    if any("_sweep_base.udb" in ln for ln in lines):
        # hqprj2tcl must regenerate run_hqprj.tcl fresh; seeing sweep markers
        # means it failed and a stale (already transformed) file is in place
        print(f"Error: {tcl_path} looks like a stale sweep TCL (hqprj2tcl may "
              f"have failed). Delete it and retry.")
        sys.exit(1)

    parts = _extract_sweep_parts(lines)
    udb_abs = os.path.abspath(os.path.join(sweep_dir, "_sweep_base.udb")).replace("\\", "/")

    # 2. synthesis once -> shared UDB, then per-seed P&R TCLs
    synth_tcl = os.path.join(sweep_dir, "run_synth.tcl")
    with open(synth_tcl, "w", encoding="utf-8", newline="") as f:
        f.write(_build_synth_tcl(parts, udb_abs))
    for seed in range(1, n + 1):
        seed_dir = os.path.join(sweep_dir, f"seed{seed}")
        if os.path.isdir(seed_dir):
            shutil.rmtree(seed_dir)  # stale files can't mix into the new run
        os.makedirs(seed_dir)
        with open(os.path.join(seed_dir, "run_hqprj.tcl"), "w",
                  encoding="utf-8", newline="") as f:
            f.write(_build_seed_tcl(parts, seed, udb_abs))

    workers = max(1, min(j, n))
    label = " (insight VLA)" if ins else ""
    print(f"Seed sweep{label}: {n} seeds, up to {workers} in parallel, on {hqprj_path}")
    print(f"Output dir: {sweep_dir}")
    print("Synthesis runs once into a shared UDB; per-seed P&R keeps effort "
          "fixed (only -seed varies).")
    started = time.time()
    _run_hqfpga(hqfpga_path, synth_tcl, sweep_dir)
    if not os.path.isfile(os.path.join(sweep_dir, "_sweep_base.udb")):
        print("Error: design.save did not produce the shared UDB; cannot run "
              "per-seed P&R. Check the synthesis log above.")
        sys.exit(1)

    # 3. parallel per-seed P&R: each seed is its own hqfpga process with
    #    cwd=<seed dir>, so nothing is shared except the read-only UDB
    elapsed_by_seed: dict = {}
    rc_by_seed: dict = {}
    queue = list(range(1, n + 1))
    running = []  # [seed, proc, logfh, started]
    try:
        while queue or running:
            while queue and len(running) < workers:
                seed = queue.pop(0)
                seed_dir = os.path.join(sweep_dir, f"seed{seed}")
                seed_tcl = os.path.join(seed_dir, "run_hqprj.tcl")
                logfh = None
                kwargs = {"cwd": seed_dir}
                if workers > 1:
                    # parallel output would interleave; capture per seed
                    logfh = open(os.path.join(seed_dir, "run.log"), "w",
                                 encoding="utf-8", errors="replace", newline="")
                    kwargs.update(stdout=logfh, stderr=subprocess.STDOUT)
                proc = subprocess.Popen([hqfpga_path, "-cmd", seed_tcl], **kwargs)
                print(f"[seed {seed}] P&R started"
                      f" ({len(running) + 1}/{workers} running)")
                running.append([seed, proc, logfh, time.time()])
            time.sleep(0.5)
            for item in running[:]:
                seed, proc, logfh, t0 = item
                if proc.poll() is None:
                    continue
                running.remove(item)
                if logfh:
                    logfh.close()
                    item[2] = None
                elapsed_by_seed[seed] = time.time() - t0
                rc_by_seed[seed] = proc.returncode
                msg = f"[seed {seed}] P&R finished in {elapsed_by_seed[seed]:.0f}s"
                if proc.returncode != 0:
                    msg += f"  (exit code {proc.returncode})"
                print(msg)
    except KeyboardInterrupt:
        for seed, proc, logfh, t0 in running:
            proc.terminate()
        for seed, proc, logfh, t0 in running:
            try:
                proc.wait(timeout=5)
            except subprocess.TimeoutExpired:
                proc.kill()
            if logfh:
                logfh.close()
        raise
    finally:
        udb_path = os.path.join(sweep_dir, "_sweep_base.udb")
        if os.path.exists(udb_path):
            os.remove(udb_path)

    # 4. collect per-seed results from the seed dirs
    results = []
    for seed in range(1, n + 1):
        seed_dir = os.path.join(sweep_dir, f"seed{seed}")
        w = _parse_wns(seed_dir, top)
        setup = w["wns_setup_ps"] if w else None
        hold = w["wns_hold_ps"] if w else None
        fmax_mhz = None
        fm = _parse_fmax(seed_dir)
        if fm:
            m = re.match(r"([\d.]+)\s*(MHz|GHz|kHz)", fm[0].get("fmax", ""))
            if m:
                val = float(m.group(1))
                fmax_mhz = {"GHz": val * 1000, "kHz": val / 1000}.get(m.group(2), val)
        bin_path = _fresh_bitstream(seed_dir, started)
        rc = rc_by_seed.get(seed)
        if bin_path:
            status = "ok"
        elif rc:
            status = f"FAIL: exit {rc}"
        else:
            status = "FAIL: no bitstream"
        results.append({"seed": seed, "setup": setup, "hold": hold,
                        "fmax_mhz": fmax_mhz, "bin": bin_path,
                        "elapsed_s": elapsed_by_seed.get(seed), "status": status})
        print(f"[seed {seed}] WNS setup={'?' if setup is None else setup} ps  "
              f"hold={'?' if hold is None else hold} ps  "
              f"{'bin=' + os.path.relpath(bin_path, sweep_dir) if bin_path else 'NO BITSTREAM'}")

    print()
    print(f"All seeds done in {time.time() - started:.0f}s.")

    # 5. summary CSV (utf-8-sig so Excel on Chinese Windows opens it cleanly)
    csv_path = os.path.join(sweep_dir, "seed_sweep_summary.csv")
    with open(csv_path, "w", encoding="utf-8-sig", newline="") as f:
        f.write("seed,wns_setup_ps,wns_hold_ps,fmax_mhz,bin,elapsed_s,status\n")
        for r in results:
            setup_c = "" if r["setup"] is None else str(r["setup"])
            hold_c = "" if r["hold"] is None else str(r["hold"])
            fmax_c = "" if r["fmax_mhz"] is None else f"{r['fmax_mhz']:.2f}"
            elapsed_c = "" if r["elapsed_s"] is None else f"{r['elapsed_s']:.0f}"
            bin_c = os.path.relpath(r["bin"], sweep_dir).replace("\\", "/") if r["bin"] else ""
            f.write(f"{r['seed']},{setup_c},{hold_c},{fmax_c},{bin_c},"
                    f"{elapsed_c},{r['status']}\n")

    print()
    print("Seed sweep summary (worst setup slack first):")
    ranked = sorted([r for r in results if r["setup"] is not None],
                    key=lambda r: r["setup"])
    for idx, r in enumerate(ranked):
        mark = "  <- best" if r is ranked[-1] else ""
        print(f"  seed {r['seed']}: setup {r['setup']} ps, hold {r['hold']} ps, "
              f"{os.path.basename(r['bin']) if r['bin'] else '?'}{mark}")
    if not ranked:
        print("  (no seed produced parseable WNS — check reports)")
    print(f"Summary CSV: {csv_path}")
    if ins:
        print()
        print("[ins] Every seed's bitstream carries the VLA probes. To capture "
              "with seed K's bit, copy it over the canonical one first:")
        print(f"      copy seed_sweep_ins\\seed<K>\\<prj>.bin "
              f"-> hqins_run\\hq_import\\hqins_impl\\  (then -insight -capture)")

    # hand off to the downloader GUI rooted at the sweep dir so picking a
    # seed's bin and flashing it is the next click; notes from the previous
    # sweep refer to regenerated seed dirs, so clear them for a clean start
    from .downloader import NOTES_FILE, spawn_gui_detached
    notes_path = os.path.join(sweep_dir, NOTES_FILE)
    if os.path.isfile(notes_path):
        os.remove(notes_path)
        print(f"Removed stale downloader notes: {notes_path}")
    if no_dl:
        print("(no_dl) Downloader GUI not launched — pick a bin from "
              f"{sweep_dir}{os.sep}seed<K>{os.sep} and download with hqbuddy -cable.")
        return
    spawn_gui_detached(cwd=sweep_dir)
    print("Downloader GUI launched (detached) in the sweep dir.")
