"""VIO (Virtual IO) runtime probe support: generate IP, register probes, read/write.

The VIO IP is an RTL module (generated by hqfpga's `vio.ip.create`) that taps the
device JTAG TAP; the standard implementation flow wires it up automatically
(``/* synthesis HQ_VIO=" " */``).  Probe widths are set by editing the generated
``defparam ...LENGTH`` values; the module template's internal probe buses are
exposed as ``probe_in`` / ``probe_out`` ports for the user to connect in RTL.

At runtime the host reads the input probe chain with
``insight.svf_generator.vio_read <bit_length>`` and drives the output probe
chain with ``vio_write -value <n>'b<bits> -radix_type Binary``.

Probe metadata lives in ``hqvla_vio/probes.json`` next to the generated module.
"""

import glob
import json
import os
import sys
import time

from . import insight


DEFAULT_MODULE = "hq_vio_ins"


def _work_dir(hqprj_arg: str | None) -> str:
    if hqprj_arg:
        hqprj = hqprj_arg
    else:
        matches = glob.glob("*.hqprj")
        if not matches:
            print("Error: no .hqprj file specified and none found in current directory.")
            sys.exit(1)
        hqprj = matches[0]
    if not os.path.isfile(hqprj):
        print(f"Error: file not found: {hqprj}")
        sys.exit(1)
    return os.path.dirname(os.path.abspath(hqprj))


def _vio_dir(work: str) -> str:
    return os.path.join(work, "hqvla_vio")


def _svf(work: str, name: str) -> str:
    return os.path.join(_vio_dir(work), name)


def _registry_path(work: str) -> str:
    return os.path.join(_vio_dir(work), "probes.json")


def load_registry(work: str) -> dict:
    path = _registry_path(work)
    if os.path.isfile(path):
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    return {"module": DEFAULT_MODULE, "inputs": [], "outputs": []}


def save_registry(work: str, reg: dict) -> None:
    os.makedirs(_vio_dir(work), exist_ok=True)
    with open(_registry_path(work), "w", encoding="utf-8") as f:
        json.dump(reg, f, indent=2, ensure_ascii=False)


def _parse_probe(spec: str) -> dict:
    """Parse 'name:width' (width optional, default 1)."""
    name, _, w = spec.rpartition(":")
    name = name or spec
    try:
        width = int(w) if w else 1
    except ValueError:
        print(f"Error: invalid probe width in '{spec}'")
        sys.exit(1)
    return {"name": name, "width": width}


def _read_die(work: str) -> str:
    matches = glob.glob(os.path.join(work, "*.hqprj"))
    if matches:
        with open(matches[0], "r", encoding="utf-8") as f:
            for line in f:
                if line.startswith("DIE="):
                    return line.split("=", 1)[1].strip()
    return ""


def _resolve_tools(work: str):
    from . import launcher

    version = launcher.resolve_hqfpga_version()
    if not version:
        print("Error: no HqFPGA installation found (use -cfg to set up).")
        sys.exit(1)
    if not version.get("has_cable"):
        print(f"Error: cable.exe not found in {version['path']}")
        sys.exit(1)
    return version["hqfpga_path"], version["cable_path"], _read_die(work)


def cmd_gen(work: str, module: str, in_width: int, out_width: int) -> None:
    """Generate the VIO IP RTL module with custom probe widths."""
    from . import launcher

    version = launcher.resolve_hqfpga_version()
    if not version:
        print("Error: no HqFPGA installation found (use -cfg to set up).")
        sys.exit(1)

    # hqfpga's vio.ip.create emits the module to a file named after the -I value
    scratch = os.path.join(work, "_vio_ip_tmp")
    tcl_path = os.path.join(work, "_hqbuddy_vio_gen.tcl")
    with open(tcl_path, "w", encoding="utf-8") as f:
        f.write(f"vio.ip.create -O {scratch} -output_module {module}\nexit\n")
    import subprocess
    try:
        subprocess.run([version["hqfpga_path"], "-cmd", tcl_path], cwd=work,
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=True)
    except subprocess.CalledProcessError:
        print("Error: vio.ip.create failed.")
        sys.exit(1)
    finally:
        if os.path.isfile(tcl_path):
            os.unlink(tcl_path)
    if not os.path.isfile(scratch):
        print(f"Error: vio.ip.create produced no output ({scratch} missing).")
        sys.exit(1)

    txt = open(scratch, encoding="utf-8", errors="replace").read()
    os.unlink(scratch)
    txt = txt.replace("defparam u_reg_in_0.LENGTH= 2;",
                      f"defparam u_reg_in_0.LENGTH= {out_width};")
    txt = txt.replace("defparam u_reg_out_0.LENGTH=1;",
                      f"defparam u_reg_out_0.LENGTH= {in_width};")
    if f"module {module} (\ninput clk\n);" in txt:
        txt = txt.replace(f"module {module} (\ninput clk\n);",
                          f"module {module} (\ninput clk,\n"
                          f"input [{in_width - 1}:0] probe_in,\n"
                          f"output [{out_width - 1}:0] probe_out\n);")
    else:
        print("Warning: module header not in expected form; probe ports not injected.")
    txt = txt.replace(".tdo(tdo1),\n\t\t.dout(dout)\n\t);",
                      ".tdo(tdo1),\n\t\t.dout(probe_out)\n\t);")
    txt = txt.replace(".tdo(tdo2),\n\t\t.din(),\n\t\t.dout()\n\t);",
                      ".tdo(tdo2),\n\t\t.din(probe_in),\n\t\t.dout()\n\t);")

    src = os.path.join(work, "src", f"{module}.v")
    os.makedirs(os.path.dirname(src), exist_ok=True)
    with open(src, "w", encoding="utf-8") as f:
        f.write(txt)
    if "probe_in" not in txt or "probe_out" not in txt:
        print("Warning: probe port injection may have failed; "
              f"review {src} manually.")

    reg = load_registry(work)
    reg["module"] = module
    reg["in_width"] = in_width
    reg["out_width"] = out_width
    save_registry(work, reg)
    print(f"[OK] VIO module generated: {src}")
    print(f"     probes: input={in_width}b (probe_in), output={out_width}b (probe_out)")
    print("Next: instantiate the module in your RTL, add the file to FILE_SRC, then")
    print("      register named probes: hqbuddy -vio -reg -in name:w [-in ...] [-out name:w ...]")


def cmd_reg(work: str, ins: list, outs: list) -> None:
    reg = load_registry(work)
    reg["inputs"] = [_parse_probe(s) for s in ins]
    reg["outputs"] = [_parse_probe(s) for s in outs]
    reg["in_width"] = sum(p["width"] for p in reg["inputs"])
    reg["out_width"] = sum(p["width"] for p in reg["outputs"])
    save_registry(work, reg)
    print(f"[OK] Probe registry saved: {_registry_path(work)}")
    def fmt(probes):
        return ", ".join(f"{p['name']}[{p['width']}b]" for p in probes) or "(none)"
    print(f"     inputs : {fmt(reg['inputs'])} (total {reg['in_width']}b)")
    print(f"     outputs: {fmt(reg['outputs'])} (total {reg['out_width']}b)")


def cmd_status(work: str) -> None:
    reg = load_registry(work)
    path = _registry_path(work)
    print(f"Registry : {path}" + ("" if os.path.isfile(path) else "  (missing)"))
    print(f"Module   : {reg.get('module', DEFAULT_MODULE)}")
    print("Inputs   : " + (", ".join(f"{p['name']}[{p['width']}b]" for p in reg.get("inputs", [])) or "(none)"))
    print("Outputs  : " + (", ".join(f"{p['name']}[{p['width']}b]" for p in reg.get("outputs", [])) or "(none)"))


def _run_svf(hqfpga_exe: str, work: str, die: str, name: str, cmd_line: str) -> None:
    cmds = [
        f"insight.svf_generator.start -svf_file_path {insight._tcl_path(_svf(work, name))} -device_die {die}",
        cmd_line,
        "insight.svf_generator.write",
    ]
    insight._run_hqfpga_cmds(hqfpga_exe, cmds, cwd=work)


def _read_raw(hqfpga_exe: str, cable_exe: str, work: str, die: str, width: int) -> int:
    _run_svf(hqfpga_exe, work, die, "vio_read.svf",
             f"insight.svf_generator.vio_read -bit_length {width}")
    tdo = insight._play_svf(cable_exe, _svf(work, "vio_read.svf"))
    vals = [v for v in tdo if v and all(c in "0123456789abcdefABCDEF" for c in v)]
    if not vals:
        print("Error: vio_read produced no TDO data (check download/JTAG).")
        sys.exit(1)
    return int(vals[-1], 16)


def cmd_read(work: str, loop: int, interval: float) -> None:
    reg = load_registry(work)
    inputs = reg.get("inputs", [])
    if not inputs:
        print("Error: no input probes registered (use -vio -reg -in name:w).")
        sys.exit(1)
    total = sum(p["width"] for p in inputs)
    hqfpga_exe, cable_exe, die = _resolve_tools(work)

    def one_read():
        raw = _read_raw(hqfpga_exe, cable_exe, work, die, total)
        # Packing: the FIRST registered probe occupies the LSB end of the read
        # value (board-verified with a rotating 8-bit pattern; opposite of the
        # raw TDO MSB-first string the GUI table uses).
        results = []
        rem = raw
        for p in inputs:
            w = p["width"]
            results.append((p["name"], rem & ((1 << w) - 1), w))
            rem >>= w
        return results

    def show():
        for name, val, w in one_read():
            hexw = max(1, (w + 3) // 4)
            print(f"  {name:20s} = 0x{val:0{hexw}X}  ({val})  [{w}b]")

    show()
    for _ in range(loop - 1):
        time.sleep(interval)
        print("  ---")
        show()


def cmd_write(work: str, assigns: list) -> None:
    reg = load_registry(work)
    outs = reg.get("outputs", [])
    if not outs:
        print("Error: no output probes registered (use -vio -reg -out name:w).")
        sys.exit(1)
    if not assigns:
        print("Error: -write needs assignments like -write led=0b10 or led=3.")
        sys.exit(1)
    values = {p["name"]: 0 for p in outs}
    for a in assigns:
        name, _, val = a.partition("=")
        if name not in values:
            print(f"Error: unknown output probe '{name}' (registered: {', '.join(values)})")
            sys.exit(1)
        v = int(val, 2) if val.startswith("0b") else int(val, 0)
        width = next(p["width"] for p in outs if p["name"] == name)
        if v >= (1 << width):
            print(f"Error: value {val} does not fit {name}[{width}b]")
            sys.exit(1)
        values[name] = v
    # GUI packing: iterate probes in registration order, prepending each value's
    # bits, so the LAST registered probe occupies the LSB end of the literal.
    out_str = ""
    for p in outs:
        out_str = format(values[p["name"]], f"0{p['width']}b") + out_str
    total = len(out_str)
    hqfpga_exe, cable_exe, die = _resolve_tools(work)
    _run_svf(hqfpga_exe, work, die, "vio_write.svf",
             f"insight.svf_generator.vio_write -value {total}'b{out_str} "
             f"-radix_type Binary -is_vla_mode False -is_multi_window False")
    insight._play_svf(cable_exe, _svf(work, "vio_write.svf"))
    print("[OK] VIO output written: " +
          ", ".join(f"{p['name']}=0x{values[p['name']]:X}" for p in outs))


def run_vio(args: list) -> None:
    """Entry point for 'hqbuddy -vio'."""
    hqprj_arg = None
    rest = []
    for a in args:
        if a.endswith(".hqprj") and hqprj_arg is None:
            hqprj_arg = a
        else:
            rest.append(a)

    work = _work_dir(hqprj_arg)

    if not rest:
        cmd_status(work)
        return

    if rest[0] == "-gen":
        module = DEFAULT_MODULE
        in_w, out_w = 8, 8
        i = 1
        while i < len(rest):
            if rest[i] == "-module" and i + 1 < len(rest):
                module = rest[i + 1]
                i += 1
            elif rest[i] == "-in" and i + 1 < len(rest):
                in_w = int(rest[i + 1])
                i += 1
            elif rest[i] == "-out" and i + 1 < len(rest):
                out_w = int(rest[i + 1])
                i += 1
            else:
                print(f"Error: unknown -gen option: {rest[i]}")
                sys.exit(1)
            i += 1
        cmd_gen(work, module, in_w, out_w)
        return

    if rest[0] == "-reg":
        ins, outs = [], []
        target = None
        for a in rest[1:]:
            if a == "-in":
                target = ins
            elif a == "-out":
                target = outs
            elif target is None:
                print(f"Error: -reg needs -in/-out before probes: {a}")
                sys.exit(1)
            else:
                target.append(a)
        cmd_reg(work, ins, outs)
        return

    if rest[0] == "-read":
        loop, interval = 1, 1.0
        i = 1
        while i < len(rest):
            if rest[i] == "-loop" and i + 1 < len(rest):
                loop = int(rest[i + 1])
                i += 1
            elif rest[i] == "-interval" and i + 1 < len(rest):
                interval = float(rest[i + 1])
                i += 1
            else:
                print(f"Error: unknown -read option: {rest[i]}")
                sys.exit(1)
            i += 1
        cmd_read(work, loop, interval)
        return

    if rest[0] == "-write":
        cmd_write(work, [a for a in rest[1:] if not a.startswith("-")])
        return

    print(f"Error: unknown -vio option: {' '.join(rest)}")
    sys.exit(1)
