`include "../../ipcore_dir/cortexM3/xsIP_cortexM3.v"
`include "../../ipcore_dir/EBR_PDP/xsIP_EBR_PDP.v"
`include "../../ipcore_dir/PLL_FREQ/xsIP_PLL_FREQ.v"
`include "../common/cmsdk_ahb_eg_slave.v"
`include "../common/cmsdk_ahb_eg_slave_interface.v"
`include "../common/cmsdk_ahb_eg_slave_reg.v"